// questions.js
const questions = [
    // Definitions & Concepts
    [span_1](start_span)"What is a program?[span_1](end_span)",
    [span_2](start_span)"Define 'programming'.[span_2](end_span)",
    [span_3](start_span)"Explain what a software is in the context of programming.[span_3](end_span)",
    [span_4](start_span)"What is the aim of the course 'Introduction to Problem Solving'?[span_4](end_span)",
    [span_5](start_span)"List two objectives of the 'Introduction to Problem Solving' course.[span_5](end_span)",
    [span_6](start_span)[span_7](start_span)[span_8](start_span)[span_9](start_span)[span_10](start_span)[span_11](start_span)"Describe two characteristics of a good programming style.[span_6](end_span)[span_7](end_span)[span_8](end_span)[span_9](end_span)[span_10](end_span)[span_11](end_span)",
    "What is a syntax error in programming? [span_12](start_span)Give an example.[span_12](end_span)",
    [span_13](start_span)"Explain semantic error with an example.[span_13](end_span)",
    "What is a logic error in programming? [span_14](start_span)[span_15](start_span)How does it differ from a syntax error?[span_14](end_span)[span_15](end_span)",
    [span_16](start_span)"Distinguish between compile-time errors and run-time errors.[span_16](end_span)",
    [span_17](start_span)"Briefly describe High Level Language programming.[span_17](end_span)",
    [span_18](start_span)"What are assembly languages?[span_18](end_span)",
    [span_19](start_span)"Explain what Low Level/Machine Language is.[span_19](end_span)",
    [span_20](start_span)[span_21](start_span)"What is the difference between strongly typed and weakly typed languages?[span_20](end_span)[span_21](end_span)",
    [span_22](start_span)"What is a 'problem' in the context of problem-solving?[span_22](end_span)",
    [span_23](start_span)[span_24](start_span)"Define 'problem solving'.[span_23](end_span)[span_24](end_span)",
    "What are the two main classifications of solutions in programming? [span_25](start_span)[span_26](start_span)Briefly describe each.[span_25](end_span)[span_26](end_span)",
    [span_27](start_span)"Compare human versus computer capabilities in problem-solving for algorithmic and heuristic solutions.[span_27](end_span)",
    [span_28](start_span)"What is the 'Abstraction' problem-solving strategy?[span_28](end_span)",
    [span_29](start_span)"Explain the 'Divide and Conquer' problem-solving strategy.[span_29](end_span)",
    [span_30](start_span)"What is 'Brainstorming' as a problem-solving technique?[span_30](end_span)",
    [span_31](start_span)"Describe the 'Means-Ends Analysis' strategy.[span_31](end_span)",
    [span_32](start_span)"What are the four main steps involved in problem-solving procedure as outlined in the notes?[span_32](end_span)",
    [span_33](start_span)[span_34](start_span)"What are the four parts of a Problem Analysis Chart?[span_33](end_span)[span_34](end_span)",
    [span_35](start_span)"What does IPO stand for in an IPO chart, and what does each part represent?[span_35](end_span)",
    [span_36](start_span)[span_37](start_span)"Define an algorithm.[span_36](end_span)[span_37](end_span)",
    [span_38](start_span)[span_39](start_span)[span_40](start_span)[span_41](start_span)[span_42](start_span)"List three properties of an algorithm.[span_38](end_span)[span_39](end_span)[span_40](end_span)[span_41](end_span)[span_42](end_span)",
    "What are the three types of control structures in algorithms? [span_43](start_span)Briefly explain 'sequence'.[span_43](end_span)",
    [span_44](start_span)"Explain 'branching (selection)' as a control structure in algorithms.[span_44](end_span)",
    [span_45](start_span)"Describe 'loop (repetition)' as a control structure in algorithms.[span_45](end_span)",
    [span_46](start_span)"What is pseudocode?[span_46](end_span)",
    [span_47](start_span)[span_48](start_span)"What is a flowchart?[span_47](end_span)[span_48](end_span)",
    [span_49](start_span)[span_50](start_span)"List two advantages of using flowcharts.[span_49](end_span)[span_50](end_span)",
    [span_51](start_span)"Explain one difference between an algorithm and a flowchart.[span_51](end_span)",
    "What is a 'constant' in BASIC programming? [span_52](start_span)[span_53](start_span)Give an example of a numeric and an alphanumeric constant.[span_52](end_span)[span_53](end_span)",
    [span_54](start_span)"What is a 'variable' in BASIC programming?[span_54](end_span)",
    [span_55](start_span)[span_56](start_span)"List the arithmetic operators in BASIC and their order of precedence.[span_55](end_span)[span_56](end_span)",
    [span_57](start_span)"What is the purpose of the LET statement in BASIC?[span_57](end_span)",
    [span_58](start_span)"Explain the difference between 'PRINT A' and 'PRINT \"A\"' in BASIC.[span_58](end_span)",
    [span_59](start_span)"What does it mean to 'debug' a program?[span_59](end_span)",
    [span_60](start_span)"Name two types of errors (bugs) that can occur in programming, as discussed in Lesson 8.[span_60](end_span)",

    // Application & Scenarios
    [span_61](start_span)"Write an algorithm to find the sum of three numbers.[span_61](end_span)",
    "Draw a simple flowchart to represent an algorithm that asks a user for their name and then prints a greeting with their name.",
    "What would be the output of the following BASIC statements? [span_62](start_span)\n10 LET A = 5\n20 LET B = 10\n30 LET C = A + B\n40 PRINT C\n50 END[span_62](end_span)",
    [span_63](start_span)"Identify the error in the BASIC statement: 10 LET X + Y = Z[span_63](end_span)",
    "A problem requires you to calculate the area of a rectangle. [span_64](start_span)Create a simple IPO chart for this problem.[span_64](end_span)",
    [span_65](start_span)"Describe how the 'Divide and Conquer' strategy could be applied to the problem of finding the largest number in a list of 1000 numbers.[span_65](end_span)",
    [span_66](start_span)[span_67](start_span)[span_68](start_span)"Explain the steps you would take to develop a solution for a problem, as per Lesson 4.[span_66](end_span)[span_67](end_span)[span_68](end_span)",
    "Using the problem-solving process, outline how you would approach calculating the circumference of a circle given the formula: circumference = 2πr. [span_69](start_span)Specifically, show the Problem Analysis Chart.[span_69](end_span)",
    [span_70](start_span)"Write an algorithm to convert temperature from Fahrenheit to Celsius using the formula Celsius = 5/9 * (Fahrenheit - 32).[span_70](end_span)",
    [span_71](start_span)"What are the 'Given Data' and 'Required Results' if you need to find the sum of even numbers between 1 and 100?[span_71](end_span)",
    [span_72](start_span)"Identify a potential logic error if a programmer uses '>' instead of '>=' when checking if a student has passed an exam (passing mark is 50).[span_72](end_span)",
    [span_73](start_span)[span_74](start_span)"If an algorithm is missing a clear stopping point, which property of algorithms is violated?[span_73](end_span)[span_74](end_span)",
    "A program is meant to calculate the average of two numbers. It correctly adds them but then multiplies by 2 instead of dividing. [span_75](start_span)What kind of error is this?[span_75](end_span)"
];
  
